@startuml slack

entity users {
  *id(pk)
  --
  username
  email
}

entity articles {
  *id(pk)
  --
  title
  content
  published_at
  external_url
  tags
  author_id
  topic_id
}

entity topics {
  *id(pk)
  --
  name
  description
}

entity tags {
  *id(pk)
  --
  name
}

entity article_tags {
  *id(pk)
  --
  article_id
  tag_id
}

entity external_services {
  *id(pk)
  --
  name
  rss
}

users o--o{ articles
topics o--o{ articles
articles o--o{ article_tags
tags o--o{ article_tags

@enduml
