FROM golang:1.18

ENV APP_ROOT /app

WORKDIR ${APP_ROOT}

RUN go install github.com/rubenv/sql-migrate/...@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . . 

RUN go build -o nozo_blog_go_api 

CMD ["./nozo_blog_go_api"]
